WIDTH  = 3.45;
HEIGHT = 2.5;
AXIS_FONT_SIZE = 7;
LEGEND_FONT_SIZE = 7;
Yaxis_NAME = 'Power (dBm/MHz)';
Xaxis_NAME = 'Frequency (MHz)';
LEGEND = {'No DPD','IM3$_{1;2,3}$','IM3$_{1;3,3}$','IM3$_{2;3,3}$'};

set(gcf, 'PaperPosition', [0 0 WIDTH HEIGHT]); %Position the plot further to the left and down. Extend the plot to fill entire paper.
set(gcf, 'PaperSize', [WIDTH HEIGHT]); %Keep the same paper size
grid on;
set(gca,...
  'TickLabelInterpreter', 'latex',...
  'FontUnits','points',...
  'FontWeight','normal',...
  'FontSize',AXIS_FONT_SIZE,...
  'FontName','Times');

ylabel(Yaxis_NAME,...
  'FontUnits','points',...
  'interpreter','latex',...
  'FontSize',AXIS_FONT_SIZE,...
  'FontName','Times')
xlabel(Xaxis_NAME,...
  'FontUnits','points',...
  'FontWeight','normal',...
  'FontSize',AXIS_FONT_SIZE,...
  'FontName','Times')
legend(LEGEND,...
  'FontUnits','points',...
  'interpreter','latex',...
  'FontSize',LEGEND_FONT_SIZE,...
  'FontName','Times',...
  'Location','south')

saveas(gcf, 'filename', 'pdf')
open('filename.pdf');