WIDTH  = 4;
HEIGHT = 3;
AXIS_FONT_SIZE = 9;
Yaxis_NAME = 'Amplitude';
Xaxis_NAME = 'Time';
LEGEND = {'entry1','entry2'};

set(gcf, 'PaperPosition', [0 0 WIDTH HEIGHT]); %Position the plot further to the left and down. Extend the plot to fill entire paper.
set(gcf, 'PaperSize', [WIDTH HEIGHT]); %Keep the same paper size

set(gca,...
  'TickLabelInterpreter', 'latex',...
  'FontUnits','points',...
  'FontWeight','normal',...
  'FontSize',AXIS_FONT_SIZE,...
  'FontName','Times');

ylabel(Yaxis_NAME,...
  'FontUnits','points',...
  'interpreter','latex',...
  'FontSize',AXIS_FONT_SIZE,...
  'FontName','Times')
xlabel(Xaxis_NAME,...
  'FontUnits','points',...
  'FontWeight','normal',...
  'FontSize',AXIS_FONT_SIZE,...
  'FontName','Times')
legend(LEGEND,...
  'FontUnits','points',...
  'interpreter','latex',...
  'FontSize',9,...
  'FontName','Times',...
  'Location','Best')

saveas(gcf, 'filename', 'pdf')
open('filename.pdf');